name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Install dependencies
        run: dotnet restore Test/Test/Test.csproj

      - name: Build
        run: dotnet build Test/Test/Test.csproj --configuration Release --no-restore
