name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create release
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Create Release
        id: create_release
        uses: rohith/publish-nuget@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
